name: Build docker image and push it to registry

on:
  workflow_call:
    inputs:
      scope:
        required: false
        type: string
        default: ""
      repository:
        required: false
        type: string
      context:
        required: false
        default: "."
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push-docker:
    name: Build and publish docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository from latest commit
        uses: actions/checkout@v4

      - name: Login to registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_PUSH_USER }}
          password: ${{ secrets.ACR_PUSH_TOKEN }}

      - name: Setup docker image name and downcase it
        run: |
          if [[ -z "${{ inputs.repository }}" ]]; then
            export DOCKER_IMAGE_NAME="${{ secrets.ACR_URL }}/${{ github.event.repository.name }}:${{ github.ref_name }}"
          else
            export DOCKER_IMAGE_NAME="${{ secrets.ACR_URL }}/${{ inputs.repository }}:${{ github.ref_name }}"
          fi
          echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME,,}" >>${GITHUB_ENV}
        shell: bash

      - name: Build docker image
        run: docker build ${{ inputs.context }} -t ${{ env.DOCKER_IMAGE_NAME }}

      - name: Push docker image
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}

  update-docker-artifact-yaml:
    uses: MapColonies/shared-workflows/.github/workflows/update-artifacts-file.yaml@master
    secrets: inherit
    needs: build-and-push-docker
    if: "${{ inputs.scope != '' }}"
    with:
      scope: ${{ inputs.scope }}
      artifact-name: ${{ inputs.repository || github.event.repository.name }}
      artifact-tag: ${{ github.ref_name }}
